# Generated by Django 5.2.4 on 2025-09-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('role', models.CharField(default='citizen', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('area_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('complaint_status', models.CharField(default='open', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.user')),
            ],
        ),
    ]
