# Generated by Django 5.2.4 on 2025-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_admin_citizen_alter_complaint_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue',
            field=models.CharField(max_length=100),
        ),
    ]
